[package]
name = "wgpu-game-of-life-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.4.0"
rand = "0.8.5"
wgpu = "26.0.1"
winit = { version = "0.30.12", features = ["rwh_05"] }
